blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ VR-Guild ê¹ƒí—ˆë¸Œ
    url: https://github.com/VRGuild/VRGuild
    about: Please ask and answer questions here.
  - name: ğŸŒ ë¬¸ì˜ ì •ë³´
    url: https://github.com/VRGuild/VRGuild/discussions
    about: ë¬¸ì˜ ì‚¬ì´íŠ¸